version: '2'
services:
  jenkins:
    image: jenkins:2.60.3-alpine
    container_name: jenkins
    restart: always
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:6.7-alpine
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    depends_on: 
      - postgres
  tomcat:
    image: tomcat:8.5-jre8-alpine
    container_name: tomcat
    restart: always
    ports: 
    - "8080:8080"
    volumes:
    - /usr/local/tomcat/webapps:/usr/local/tomcat/webapps
    - /usr/local/tomcat/logs:/usr/local/tomcat/logs
  nexus:
    image: sonatype/nexus
    container_name: nexus
    restart: always
    volumes:
    - /var/nexus:/sonatype-work
    ports: 
    - "8081:8081"